baseURL = "https://tetsuyainfra.github.io/"
languageCode = "ja-JP"
HasCJKLanguage = true
title = "tetsuyainfra"
#theme = "blackburn"
theme = "my-blackburn"
author = "tetsuyainfra"
copyright = "(c) 2018 tetsuyainfra"
canonifyurls = true
paginate = 10
defaultContentLanguage = "ja"

[params]
googleAnalytics = "Your Google Analytics tracking ID"
disqus = "Your Disqus shortname"
# CSS name for highlight.js
highlightjs = "androidstudio"
brand = "@tetsuyainfra"
subtitle = "日々是好日"
dateFormat = "2006/01/02 15:04:05 MST"
contentListDateFormat = "01/02 15:04:05 MST"

[languages]
[languages.ja]
  languageName = "日本語"
  weight = 1
  [languages.ja.params]
    subtitle = "日々是好日"
    description = "tetsuyainfra's diary"

[languages.en]
  languageName = "English"
  weight = 2
  [languages.en.params]
    subtitle = "Good day every day"
    description = "tetsuyainfra's diary"

[indexes]
  tag = "tags"
  topic = "topics"


[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "日記"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "Factorio"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 3
    identifier = "factorio"
    url = "/factorio/"
  [[menu.main]]
    name = "Link"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 4
    identifier = "link"
    url = "/link/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 100
    identifier = "about"
    url = "/about/"
#  [[menu.main]]
#    name = "Contact"
#    pre = "<i class='fa fa-phone fa-fw'></i>"
#    weight = 4
#    url = "/contact/"

[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.
#  twitter = "*"
#  facebook = "*"
#  instagram = "*"
  github = "tetsuyainfra"
#  stackoverflow = "*"
#  linkedin = "*"

