version: "3"
services:
  hugosite: &hugobase
    build:
      context: ./docker_image
      args:
        # APP_UID: 1000
        # APP_GID: 1000
        APP_UID: ${APP_UID}
        APP_GID: ${APP_GID}
    image: "hugobase:latest"
    command: hugo --source site
    working_dir: /home/appusr/project
    volumes:
      - ${PRJ_ROOT}:/home/appusr/project

  hugoserv: 
    command: hugo server --source site --baseURL http://localhost:1313/ --bind=0.0.0.0 --watch
    image: "hugobase:latest"
    working_dir: /home/appusr/project
    volumes:
      - ${PRJ_ROOT}:/home/appusr/project
    ports:
      - "1313:1313"
