version: 2


############################################################
jobs:
  docker_build:
    machine: true
    steps:
      - checkout
      - run: |
          echo "run docker build"

  diary_build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: |
          echo "diary build"


############################################################
workflows:
  version: 2        
  # Dockerイメージのビルド&デプロイ
  docker_jobs:
    jobs:
      - docker_build:
          filters:
            branches:
              only: /^docker-master/

  # 日記の更新
  diary_jobs:
    jobs:
      - diary_build:
          filters:
            branches:
              ignore: /^docker-.*/

