version: 2


############################################################
jobs:
  docker_build:
    machine: true
    steps:
      - checkout
      - run: |
          TAG=`grep "ENV HUGO_VERSION" docker_image/Dockerfile | awk '{ print $3 }'`
          echo "TAG: ${TAG}"
          docker image build --tag tetsuyainfra/hugobase:${TAG} docker_image/ 

          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push tetsuyainfra/hugobase:${TAG}

  diary_build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: |
          echo "diary build"


############################################################
workflows:
  version: 2        
  # Dockerイメージのビルド&デプロイ
  docker_jobs:
    jobs:
      - docker_build
      # - docker_build:
      #     filters:
      #       branches:
      #         only: /^docker-master/

  # 日記の更新
  diary_jobs:
    jobs:
      - diary_build:
          filters:
            branches:
              ignore: /^docker-.*/

