version: 2


############################################################
jobs:
  docker_build:
    machine: true
    steps:
      - checkout
      - run: |
          TAG=`grep "ENV HUGO_VERSION" docker_image/Dockerfile | awk '{ print $3 }'`
          docker image build --tag tetsuyainfra/hugobase:${TAG} docker_image/ 
          docker tag tetsuyainfra/hugobase:${TAG} tetsuyainfra/hugobase:latest
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: |
          TAG=`grep "ENV HUGO_VERSION" docker_image/Dockerfile | awk '{ print $3 }'`
          docker push tetsuyainfra/hugobase:${TAG}
          docker push tetsuyainfra/hugobase:latest

  diary_build:
    docker:
      - image: tetsuyainfra/hugobase:latest
    working_directory: ~/project
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: |
          hugo --source ./site
      - persist_to_workspace:
          root: .
          paths:
            - site/public

  diary_deploy:
    docker:
      - image: tetsuyainfra/hugobase:latest
    working_directory: ~/project
    steps:
      - add_ssh_keys:
          fingerprints: "30:b6:36:96:cd:0c:f9:8e:a0:6e:76:5b:7c:4a:10:ec"
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - attach_workspace:
          at: ~/project
      - run: ls -la .
      - run: ls -la site/
      - run: ls -la site/public
      - run: |
          git config --global user.name "${GIT_USER}"
          git config --global user.email "${GIT_EMAIL}"
      - run: git status
      - run: |
          GIT_COMMIT_DESC=$(git log --format=oneline -n 1 $CIRCLE_SHA1)
          cd site/public
          git status
          git add .
          git commit -m "Auto build: ${GIT_COMMIT_DESC} [ci skip]"
          git push git@github.com:tetsuyainfra/tetsuyainfra.github.io master

############################################################
workflows:
  version: 2        
  # Dockerイメージのビルド&デプロイ
  docker_jobs:
    jobs:
      - docker_build:
          filters:
            branches:
              only: /^docker-master/

  # 日記の更新
  diary_jobs:
    jobs:
      - diary_build:
          filters:
            branches:
              ignore: /^docker-.*/
      - diary_deploy:
          requires: [ diary_build ]
          filters:
            branches:
              only: /^master/

