version: 2


############################################################
jobs:
  docker_build:
    machine: true
    steps:
      - checkout
      - run: |
          TAG=`grep "ENV HUGO_VERSION" docker_image/Dockerfile | awk '{ print $3 }'`
          docker image build --tag tetsuyainfra/hugobase:${TAG} docker_image/ 
          docker tag tetsuyainfra/hugobase:${TAG} tetsuyainfra/hugobase:latest
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: |
          TAG=`grep "ENV HUGO_VERSION" docker_image/Dockerfile | awk '{ print $3 }'`
          docker push tetsuyainfra/hugobase:${TAG}
          docker push tetsuyainfra/hugobase:latest

  diary_build:
    docker:
      - image: tetsuyainfra/hugobase:latest
    working_directory: ~/project
    steps:
      - checkout
      - run: |
          hugo --source ./site
      - persist_to_workspace:
          root: .
          paths:
            - site/public

  diary_deploy:
    docker:
      - image: tetsuyainfra/hugobase:latest
    working_directory: ~/project
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: ls -la site/public
      - attach_workspace:
          at: ~/project
      - run: ls -la .
      - run: ls -la site/
      - run: ls -la site/public
      - run: |
          git config --global user.name "${GIT_USER}"
          git config --global user.email "${GIT_EMAIL}"


############################################################
workflows:
  version: 2        
  # Dockerイメージのビルド&デプロイ
  docker_jobs:
    jobs:
      - docker_build:
          filters:
            branches:
              only: /^docker-master/

  # 日記の更新
  diary_jobs:
    jobs:
      - diary_build:
          filters:
            branches:
              ignore: /^docker-.*/
      - diary_deploy:
          requires: [ diary_build ]
          filters:
            branches:
              only: /^master/

